### ISSUE TITLE
Cart Abandonment Chart (visual)

### ISSUE THREAD

**Issue by alexjcollins** [bymayo/craft-commerce-widgets#10]
Sorry, me again!

Getting a couple of weird issues with the Abandoned Cart widget:

1. y axis values appear to be getting bunched up on the left
2. graph appears to have a max width when being used at a wider setting on the dashboard.

Cheers!

![screenshot 2018-10-15 at 07 48 56](https://user-images.githubusercontent.com/12031196/46934393-7f356680-d04f-11e8-813f-d5ca932f87da.png)

**Comment by bymayo** [comment]
Will fix these issues (Responsive is high on the list at the moment) 

But, WOW, that's a lot of carts! :) Will push a fix for this today.

**Comment by bymayo** [comment]
@alexjcollins Can you upgrade to `2.0.8` and see if that fixes your issues.

If it still looks a bit wonky, can you hit me up on Slack - @bymayo as I don't have stores with that amount of carts to test with.

**Comment by alexjcollins** [comment]
@bymayo That's sorted it for me! One again, thanks for fixing so quickly!

**Comment by bymayo** [comment]
@alexjcollins Thats good news 👍 I've just made it so the Y Axis amount will never be more than 5 as I think this looks neater.

No problem! Trying to squash bugs as they come in 😎
