### ISSUE TITLE
Completed carts figure incorrect

### ISSUE THREAD

**Issue by fantasticmachine** [bymayo/craft-commerce-widgets#11]
There's an issue with the number being reported for completed carts.

The method currently uses the dateCreated attribute in the query to get the completed carts. But it's possible for a cart to be created on say a Monday but not ordered (and thus completed) until the Tuesday.

In order to get an accurate figure for completed carts it's necessary to look at the dateOrdered attribute instead but still use the dateCreated for getting the abandoned carts figure.

**Comment by fantasticmachine** [comment]
I've created a pull request with what I think is a fix for this.

**Comment by bymayo** [comment]
@fantasticmachine Thanks for submitting the pull request. It does seem that the carts were off. I've committed this now 👍
