### ISSUE TITLE
Total Ordered value incorrect

### ISSUE THREAD

**Issue by alexjcollins** [bymayo/craft-commerce-widgets#15]
I'm _definitely_ not sure, but it looks like the `Total Ordered` or `Total Revenue` value is showing the number of times the product appears in orders rather than data unique to that item.

For example, for a given product on the widget we see:
- 909 Total Ordered
- £19,599 Total Revenue

We know the product in question is £7 so if the total ordered is correct the total revenue should be £6,363.

If the total revenue is correct, the data must be made of multiple sources, since 19599 isn't divisible by 7 (and I'm pretty sure there are no historic discounts that would affect data).

Bit of a strange one - I know there's a discrepancy but I'm really not sure where 🧐

**Comment by bymayo** [comment]
@alexjcollins Hmmm that's strange, I'll look in to this - Certainly looks like a miss calculation issue.

Are all the products in the same currency? 

I'll find a fix and push later this week

**Comment by alexjcollins** [comment]
@bymayo epic thanks.
Yeah everything is in GBP on that site. Happy to ping stuff over that you might to help debug.

**Comment by alexjcollins** [comment]
Thought I'd do a bit more digging to help you out with finding more intel on this.

So we've extended Commerce's export with a left join for the line item variants and the total of that line item.

Here's a gist for the updated reports file, if you wanted to have a play:
https://gist.github.com/alexjcollins/4a2edbd692c70c7ab74492b3536f1e97
Lines `70`,`71` and `86` were added.

I decided to total the variant in the example above using the report data and I got £15,099 (which gives a quantity total of 2157). So I'm wondering if both the Total Revenue and the Total Ordered are incorrect?

Incidentally, we ran a report with and without our changes across all products and we were out by £12 (total was over 40k) so I'm trying to get to the bottom of that one. Probably me missing something on my count in the spreadsheet!

**Comment by bymayo** [comment]
@alexjcollins I've been trying to fix this issue but it's proving tricky when the site only has a few orders (As the values are correct).

Is there anyway I could get a copy of your `commerce_orders` and `commerce_lineitems` tables (Hopefully thats all I need) to fix this issue? 

I don't think theres anything confidential in there apart from `email` column if you want to blank that out.

**Comment by alexjcollins** [comment]
@bymayo Sure, I'll whizz them over on Slack

**Comment by bymayo** [comment]
Fixed in latest release 👍 

Thanks for helping me out by sending over the database over 💯
