### ISSUE TITLE
Issues with Verbb Gift Voucher

### ISSUE THREAD

**Issue by marc524** [bymayo/craft-commerce-widgets#20]
When using Verbb's Gift Voucher plugin, Vouchers are available in **commerce_purchasables**, but are not in **commerce_variants**. As such, the query returns _NULL_ for the ID and SKU. This really messes up the widget.

My solution right now is to just exclude any item the returns a NULL ID. This actually gives me what I want the most anyway, as I just want to know what the actual top selling products are and exclude Gift Vouchers from that display.

Change Line 84 of ProductsTop.php from
```
->where(['orders.orderStatusId' => $this->orderStatusId]);
```

to
```
->andWhere(['orders.orderStatusId' => $this->orderStatusId])
->andWhere(['not', ['variants.productId' => null]]);
```

I could see this also being an issue with Digital Products, as those products don't use Variants either, although I haven't tested it.

**Comment by bymayo** [comment]
@marc524 Thanks for letting me know about this. I'll test that line and merge. If you want to submit a pull request you can do that also with the fix.

**Comment by bymayo** [comment]
@marc524 Fixed in latest release.
