### ISSUE TITLE
Trashed orders are being included in all totals

### ISSUE THREAD

**Issue by mediabeastnz** [bymayo/craft-commerce-widgets#27]
It seems all totals for revenue etc are including orders that have been trashed. 

We had a lot of test orders which were trashed rather than deleted from the database so totals are way out.

**Comment by bymayo** [comment]
Sorry about that - It must have been since the update to Craft 3.1 / 3.2. I'll push a fix for this.

**Comment by bymayo** [comment]
@mediabeastnz This has been fixed in `2.0.17`, update to get these bug fixes. You may see a drop/change in your stats with this fix.

Also just ensure your on Craft CMS 3.2.x

**Comment by mediabeastnz** [comment]
Legend!
