### ISSUE TITLE
FR: Ability to exclude orders from specific emails

### ISSUE THREAD

**Issue by mediabeastnz** [bymayo/craft-commerce-widgets#28]
**Feature Request**

It would be awesome if there was a setting to exclude specific email addresses from all the widgets.

For example the client and our team often make test orders which can through out totals like abandoned carts etc.

**Comment by bymayo** [comment]
That's a good idea! I'll add this in as a config setting to exclude email addresses / customers.

**Comment by bymayo** [comment]
This has been added to `2.0.17`, see the read me for more information on how to do this - https://github.com/bymayo/craft-commerce-widgets#configuration
