### ISSUE TITLE
Number of orders over all time

### ISSUE THREAD

**Issue by terryupton** [bymayo/craft-commerce-widgets#7]
Would be great to add to the Total Revenue & Orders widget the total orders over all time. 
Currently shows the year, month, week, yesterday and today. A bottom figure for ALL time would be great.

**Comment by bymayo** [comment]
Just added this to the widget 💯 

I've also moved it to a new branch so make sure you update 👍

**Comment by terryupton** [comment]
Perfect thanks @bymayo
