### ISSUE TITLE
Timestamps Off from Craft install

### ISSUE THREAD

**Issue by mobiusint** [bymayo/craft-commerce-widgets#8]
Hi there!
Great plugin! We love it, would you happen to know why the timestamps are off from what our craft install is set at? Is there somewhere to set the timezone to EST?

Thank you

**Comment by bymayo** [comment]
It's nice to hear people using this plugin :) (Craft3 coming as soon as I get a Commerce 2 beta invite!)

With the timestamps, i'm unsure without diving deeper! Is it all of the widgets that are off, or just a particular one?

**Comment by mobiusint** [comment]
Hey there, yes these widgets are awesome! I think it's mainly the total revenue & orders and the revenue one. They seem to show up in Pacific time. Also the two widgets may show slightly different timezones, it's very strange. It seems as though some widgets use the correct timezone and then some are offset a little bit. Is there an area where you are setting the timezone in php?
